name:                tangler
version:             0.1.0.0
github:              "githubuser/tangler"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/tangler#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  tangler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tangler
    - megaparsec
    - text

tests:
  tangler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tangler
